# Generated by Django 5.2.7 on 2025-10-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ESPETO', 'Espeto'), ('BEBIDA', 'Bebida'), ('ACOMPANHAMENTO', 'Acompanhamento')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estoque', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
