# Generated by Django 5.2.7 on 2025-12-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_alter_itemcardapio_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='categoria',
            field=models.CharField(choices=[('ESPETO', 'Espeto'), ('BEBIDA', 'Bebida'), ('ACOMPANHAMENTO', 'Acompanhamento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
